create database college_management;
use college_management;
create table student_details(name varchar(55)not null,id int not null primary key,sex varchar(55)not null,city varchar(55) not null);
describe table student_details;
insert into student_details values('Vignesh',1,'M','Perungalathur');
insert into student_details values('Naveen',2,'M','Chrompet');
insert into student_details values('Maha',3,'F','Porur');
insert into student_details values('Nandhini',4,'F','Tambaram');
alter table student_details add age varchar(23);
select*from student_details;
update student_details set age=21 where id=1;
select*from student_details;
delete from student_details where id=3;
select*from student_details;
update student_details set age=21 where id=2;
update student_details set age=21 where id=4;
select*from student_details;
